
---
- name: installing apache2 server
  hosts: deb-based
  become: yes

  vars:
   src_file: ../files/simple_web_page/index.html
   dst_file: /var/www/html

  tasks:
  - name: installing apache2 on deb-systems
    ansible.builtin.apt: name=apache2 state=latest

  - name: copy simple page to servers
    copy: src={{ src_file }} dest={{dst_file}} mode=0555
    notify: restarting apache2 to apply changes

  - name: start apache2 and add to enabled services
    service: name=apache2 state=started enabled=yes

  handlers:
  - name: restarting apache2 to apply changes
    service: name=apache2 state=restarted
